# Basic
hard_tabs = true
max_width = 100
use_small_heuristics = "Max"
# Consistency
newline_style = "Unix"
# Misc
chain_width = 80
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
use_field_init_shorthand = true
edition = "2021"
