[package]
name = "node-cli"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Generic Substrate node implementation in Rust."
build = "build.rs"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
default-run = "substrate"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[badges]
travis-ci = { repository = "paritytech/substrate" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[[bin]]
name = "substrate"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
array-bytes = "4.1"
clap = { version = "4.0.9", features = ["derive"], optional = true }
codec = { package = "parity-scale-codec", version = "3.0.0" }
serde = { version = "1.0.136", features = ["derive"] }
jsonrpsee = { version = "0.15.1", features = ["server"] }
futures = "0.3.21"
log = "0.4.17"
rand = "0.8"

# primitives
sp-authority-discovery = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-consensus-babe = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
grandpa-primitives = { version = "4.0.0-dev", package = "sp-finality-grandpa", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-api = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-core = { version = "6.0.0", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-runtime = { version = "6.0.0", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-timestamp = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-authorship = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-inherents = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-keyring = { version = "6.0.0", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-keystore = { version = "0.12.0", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-consensus = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-transaction-pool = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-transaction-storage-proof = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }

# client dependencies
sc-client-api = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-chain-spec = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-consensus = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-transaction-pool = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-transaction-pool-api = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-network = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-network-common = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-consensus-slots = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-consensus-babe = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-consensus-uncles = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
grandpa = { version = "0.10.0-dev", package = "sc-finality-grandpa", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-rpc = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-basic-authorship = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-service = { version = "0.10.0-dev", default-features = false, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-telemetry = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-executor = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-authority-discovery = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-sync-state-rpc = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-sysinfo = { version = "6.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }

# frame dependencies
frame-system = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
frame-system-rpc-runtime-api = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
pallet-transaction-payment = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
pallet-asset-tx-payment = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
pallet-im-online = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }

# node-specific dependencies
kitchensink-runtime = { version = "3.0.0-dev", path = "../runtime" }
node-rpc = { version = "3.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
node-primitives = { version = "2.0.0", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
node-executor = { version = "3.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }

# CLI-specific dependencies
sc-cli = { version = "0.10.0-dev", optional = true, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
frame-benchmarking-cli = { version = "4.0.0-dev", optional = true, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
node-inspect = { version = "0.9.0-dev", optional = true, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
try-runtime-cli = { version = "0.10.0-dev", optional = true, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
serde_json = "1.0.85"

[target.'cfg(any(target_arch="x86_64", target_arch="aarch64"))'.dependencies]
node-executor = { version = "3.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate", features = ["wasmtime"] }
sc-cli = { version = "0.10.0-dev", optional = true, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate", features = ["wasmtime"] }
sc-service = { version = "0.10.0-dev", default-features = false, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate", features = [
	"wasmtime",
] }
sp-trie = { version = "6.0.0", default-features = false, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate", features = [
	"memory-tracker",
] }

[dev-dependencies]
sc-keystore = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-client-db = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-consensus = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-consensus-babe = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-consensus-epochs = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-service-test = { version = "2.0.0", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-block-builder = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-tracing = { version = "5.0.0", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sp-blockchain = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
futures = "0.3.21"
tempfile = "3.1.0"
assert_cmd = "2.0.2"
nix = "0.23"
serde_json = "1.0"
regex = "1.6.0"
platforms = "2.0"
async-std = { version = "1.11.0", features = ["attributes"] }
soketto = "0.7.1"
criterion = { version = "0.3.5", features = ["async_tokio"] }
tokio = { version = "1.17.0", features = ["macros", "time", "parking_lot"] }
wait-timeout = "0.2"
substrate-rpc-client = { branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
pallet-timestamp = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }

[build-dependencies]
clap = { version = "4.0.9", optional = true }
clap_complete = { version = "4.0.2", optional = true }
node-inspect = { version = "0.9.0-dev", optional = true, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
frame-benchmarking-cli = { version = "4.0.0-dev", optional = true, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
substrate-build-script-utils = { version = "3.0.0", optional = true, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
substrate-frame-cli = { version = "4.0.0-dev", optional = true, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
try-runtime-cli = { version = "0.10.0-dev", optional = true, branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }
sc-cli = { version = "0.10.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate", optional = true }
pallet-balances = { version = "4.0.0-dev", branch = "polkadot-v0.9.33", git = "https://github.com/paritytech/substrate" }

[features]
default = ["cli"]
cli = [
	"node-inspect",
	"sc-cli",
	"frame-benchmarking-cli",
	"substrate-frame-cli",
	"sc-service/rocksdb",
	"clap",
	"clap_complete",
	"substrate-build-script-utils",
	"try-runtime-cli",
]
runtime-benchmarks = [
	"kitchensink-runtime/runtime-benchmarks",
	"frame-benchmarking-cli/runtime-benchmarks"
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["kitchensink-runtime/try-runtime", "try-runtime-cli/try-runtime"]

[[bench]]
name = "transaction_pool"
harness = false

[[bench]]
name = "block_production"
harness = false
